# Generated by Django 2.2.10 on 2020-05-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('stock', models.IntegerField(default=1)),
                ('disponible', models.CharField(choices=[('0', 'No'), ('1', 'Si')], max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en ₡', max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
