# Generated by Django 2.2.10 on 2020-05-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20200507_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disponible',
        ),
    ]
