# Generated by Django 2.2.10 on 2020-05-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20200507_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tipo',
        ),
        migrations.AddField(
            model_name='category',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Type'),
            preserve_default=False,
        ),
    ]
