# Generated by Django 2.2.10 on 2020-05-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20200507_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Type'),
            preserve_default=False,
        ),
    ]
