# Generated by Django 2.2.10 on 2020-05-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_product_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Type'),
            preserve_default=False,
        ),
    ]
